"""Initial migration

Revision ID: 7de682af9779
Revises: 
Create Date: 2025-03-27 04:59:43.755306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de682af9779'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table('users',
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False, server_default='anotador'),
        sa.PrimaryKeyConstraint('username'),
        sa.UniqueConstraint('email')
    )
    
    # Create responses table
    op.create_table('responses',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('response', sa.Text(), nullable=False),
        sa.Column('translation', sa.Text(), nullable=False),
        sa.Column('human', sa.Text(), nullable=False),
        sa.Column('conversation_id', sa.String(255), nullable=True),
        sa.Column('tutor_identity', sa.String(255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create conversations table
    op.create_table('conversations',
        sa.Column('conversation_id', sa.String(255), nullable=False),
        sa.Column('conversation_history', sa.Text(), nullable=False),
        sa.Column('translation', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('conversation_id')
    )

    # Create entropies table
    op.create_table('entropies',
        sa.Column('conversation_id', sa.String(255), nullable=False),
        sa.Column('tutor_identity', sa.String(255), nullable=True),
        sa.Column('entropy', sa.Float(), nullable=False),
        sa.Column('assigned', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('annotated', sa.Boolean(), nullable=False, server_default='false'),
        sa.PrimaryKeyConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entropies')
    op.drop_table('conversations')
    op.drop_table('responses')
    op.drop_table('users')
    # ### end Alembic commands ###
